[package]
name = "b-matching-triple-sum-product"
version = "0.1.0"
authors = ["Galus <mgalus@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
